services:
  redis:
    image: redis/redis-stack:latest
    container_name: semantic-cache-redis
    ports:
      - "6379:6379"
      - "8001:8001"  
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - semantic-cache-network

volumes:
  redis-data:

networks:
  semantic-cache-network:
    driver: bridge
